name                = "banproof-me"
main                = "src/index.ts"
compatibility_date  = "2026-04-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"
USE_MOCK    = "true"
CF_ACCESS_AUDIENCE = "18f2fecc663c66d5de8fd7b6c08def28b0496216669af44abf51ac221b6b40e5"

[[routes]]
pattern   = "api.banproof.me/*"
zone_name = "banproof.me"

[[routes]]
pattern   = "admin.banproof.me/*"
zone_name = "banproof.me"

[env.production.vars]
ENVIRONMENT = "production"
USE_MOCK = "true"

[[env.production.routes]]
pattern   = "api.banproof.me/*"
zone_name = "banproof.me"

[[env.production.routes]]
pattern   = "admin.banproof.me/*"
zone_name = "banproof.me"

[env.staging.vars]
ENVIRONMENT = "staging"
USE_MOCK = "true"

[[env.staging.routes]]
pattern   = "api.banproof.me/*"
zone_name = "banproof.me"

[[env.staging.routes]]
pattern   = "admin.banproof.me/*"
zone_name = "banproof.me"

[env.preview.vars]
ENVIRONMENT = "preview"
USE_MOCK = "true"

[[env.preview.routes]]
pattern   = "api.banproof.me/*"
zone_name = "banproof.me"

[[env.preview.routes]]
pattern   = "admin.banproof.me/*"
zone_name = "banproof.me"

[observability]
enabled = true
